create or replace trigger trg_audit
after update or delete
on LDS_Placement
for each row
Declare
v_id number;
begin
If updating THEN
Begin
If (:Old.PTL_ACTUAL_START_DATE<> :New.PTL_ACTUAL_START_DATE) Then
begin
Insert into AuditRecord(COLUMNNAME,OLDVALUE,NEWVALUE,PRIMARYID,PRIMARYKEY,OPERATION,TABLENAME,AUDITEDBY) Values ('PTL_ACTUAL_START_DATE',to_char(:old.PTL_ACTUAL_START_DATE),to_char(:new.PTL_ACTUAL_START_DATE),to_char(:old.PLACEMENT_ID),'PLACEMENT_ID','Update','LDS_PLACEMENT',V('APP_USER'));
end;
end if;
If (:Old.PLT_ACTUAL_END_DATE<> :New.PLT_ACTUAL_END_DATE) Then
begin
Insert into AuditRecord(COLUMNNAME,OLDVALUE,NEWVALUE,PRIMARYID,PRIMARYKEY,OPERATION,TABLENAME,AUDITEDBY) Values ('PLT_ACTUAL_END_DATE',to_char(:old.PLT_ACTUAL_END_DATE),to_char(:new.PLT_ACTUAL_END_DATE),to_char(:old.PLACEMENT_ID),'PLACEMENT_ID','Update','LDS_PLACEMENT',V('APP_USER'));
end;
end if;
If (:Old.ACTUAL_SALARY<> :New.ACTUAL_SALARY) Then
begin
Insert into AuditRecord(COLUMNNAME,OLDVALUE,NEWVALUE,PRIMARYID,PRIMARYKEY,OPERATION,TABLENAME,AUDITEDBY) Values ('ACTUAL_SALARY',to_char(:old.ACTUAL_SALARY),to_char(:new.ACTUAL_SALARY),to_char(:old.PLACEMENT_ID),'PLACEMENT_ID','Update','LDS_PLACEMENT',V('APP_USER'));
end;
end if;
END;
End If;

If deleting THEN
begin
Insert into AuditRecord(COLUMNNAME,OLDVALUE,NEWVALUE,PRIMARYID,PRIMARYKEY,OPERATION,TABLENAME,AUDITEDBY)
    Values ('','','',to_char(:old.PLACEMENT_ID),'PLACEMENT_ID','Delete','LDS_PLACEMENT',V('APP_USER'))
    returning AuditRecordId into v_id;
Insert into LDS_PLACEMENT_AUDITDELETE (AUDITID,PLACEMENT_ID,PLT_SHORT_DESC,PLT_REQUIRED_START_DATE,PLT_ESTIMATED_END_DATE,PTL_ACTUAL_START_DATE,PLT_ACTUAL_END_DATE,PLT_RENEWAL_NO,
PLT_TO_PERMANENT,MAX_SALARY,MIN_SALARY,ACTUAL_SALARY,FK1_ACCOUNT_ID,FK2_CONTRACTOR_ID,FK3_JOB_ROLE_ID,CREATEDBY,CREATEDDATE,UPDATEDBY,UpdatedDate) 
values 
(v_id,:old.PLACEMENT_ID,:old.PLT_SHORT_DESC,:old.PLT_REQUIRED_START_DATE,:old.PLT_ESTIMATED_END_DATE,:old.PTL_ACTUAL_START_DATE,:old.PLT_ACTUAL_END_DATE,:old.PLT_RENEWAL_NO,
:old.PLT_TO_PERMANENT,:old.MAX_SALARY,:old.MIN_SALARY,:old.ACTUAL_SALARY,:old.FK1_ACCOUNT_ID,:old.FK2_CONTRACTOR_ID,:old.FK3_JOB_ROLE_ID,:old.CREATEDBY,:old.CREATEDDATE,:old.UpdatedBy,
:old.UpdatedDate);
end;
End if;
end;
