create or replace package "WH_PKG" is
    
PROCEDURE load_LOCALAUTHORITY (p_recordset OUT SYS_REFCURSOR);
PROCEDURE load_region (p_recordset OUT SYS_REFCURSOR);
PROCEDURE load_time (p_recordset OUT SYS_REFCURSOR);
PROCEDURE load_ROADTYPE(p_recordset OUT SYS_REFCURSOR) ;
PROCEDURE load_VEHICLETYPE(p_recordset OUT SYS_REFCURSOR) ;
PROCEDURE load_ROAD(p_recordset OUT SYS_REFCURSOR) ;
PROCEDURE load_Fact_FUNDAMENTALS (p_recordset OUT SYS_REFCURSOR) ;
    
procedure Data_quality_check(pv_rows OUT NUMBER);
PROCEDURE DIM_LOAD_REGION;
PROCEDURE DIM_LOAD_LOCALAUTHORITY ;
PROCEDURE DIM_LOAD_ROADTYPE;
PROCEDURE DIM_LOAD_VEHICLETYPE;
PROCEDURE DIM_LOAD_time ;
PROCEDURE DIM_LOAD_ROAD;
 
PROCEDURE FACT_LOAD_CARS(counter OUT NUMBER);
PROCEDURE FACT_LOAD_PEDALCYCLE (counter OUT NUMBER);PROCEDURE FACT_LOAD_MOTORCYCLE(counter OUT NUMBER);
PROCEDURE FACT_LOAD_BUSESCOACHES(counter OUT NUMBER);PROCEDURE FACT_LOAD_LIGHTGOODSVEHICLES(counter OUT NUMBER);
PROCEDURE FACT_LOAD_V2AXLERIGIDHGV(counter OUT NUMBER);PROCEDURE FACT_LOAD_V3AXLERIGIDHGV(counter OUT NUMBER);
PROCEDURE FACT_LOAD_V3OR4AXLEARTICHGV(counter OUT NUMBER);PROCEDURE FACT_LOAD_V4OR5AXLERIGIDHGV(counter OUT NUMBER);
PROCEDURE FACT_LOAD_V5AXLEARTICHGV(counter OUT NUMBER);PROCEDURE FACT_LOAD_V6ORMOREAXLEARTICHGV(counter OUT NUMBER);
END WH_PKG;
